spring:
  application:
    name: shipment-service
    data:
      redis:
        host: localhost
        port: 6379
  flyway:
    url: jdbc:mysql://localhost:3306/your_database
    user: your_username
    password: your_password
    baseline-on-migrate: true
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=60m
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
