spring:
  application:
    name: shipment-service
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=60m
  flyway:
    locations: classpath:db/migration
  kafka:
    producer:
      value-serializer: com.danijelsudimac.shipmentservice.util.CustomJsonSerializer
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: shipment-service