spring:
  data:
    redis:
      password: ${SPRING_DATA_REDIS_AUTH_TOKEN}
      ssl:
        enabled: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN

      sasl.jaas.config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${SPRING_KAFKA_API_KEY}"
        password="${SPRING_KAFKA_API_SECRET}";

    consumer:
      group-id: shipment-group
      auto-offset-reset: earliest