spring:
  autoconfigure:
    # 1. Potpuno gašenje unutrašnjeg pokretanja drajvera i konekcija
    exclude:
      # Isključivanje PostgreSQL-a (JPA i DataSources)
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      # Isključivanje Kafka konekcije
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration