spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/api_key_database
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/api_key_database
    user: test
    password: test
    baseline-on-migrate: true
kafka:
  bootstrap-servers: localhost:9092
logging:
  structured:
    format:
      console: logstash