{
  "type" : "record",
  "name" : "ShipmentCreatedEvent",
  "namespace" : "com.danijelsudimac.shipmentservice.model.event",
  "fields" : [ {
    "name" : "idempotencyKey",
    "type": [
      "null",
      "string"
    ],
    "default": null
  }, {
    "name" : "carrier",
    "type": [
      "null",
      "string"
    ],
    "default": null
  }, {
    "name" : "clientId",
    "type": [
      "null",
      "long"
    ],
    "default": null
  }, {
    "name" : "createdAt",
    "type": [
      "null",
      {
        "type": "long",
        "logicalType": "timestamp-millis"
      }],
    "default": null
  }, {
    "name" : "estimatedDelivery",
    "type": [
      "null",
      {
        "type": "long",
        "logicalType": "timestamp-millis"
      }],
    "default": null
  }, {
    "name" : "estimatedPickup",
    "type": [
      "null",
      {
        "type": "long",
        "logicalType": "timestamp-millis"
      }],
    "default": null
  }, {
    "name" : "eventTimestamp",
    "type": [
      "null",
      {
        "type": "long",
        "logicalType": "timestamp-millis"
      }],
    "default": null
  }, {
    "name" : "externalId",
    "type": [
      "null",
      "string"
    ],
    "default": null
  }, {
    "name" : "goods",
    "type" : ["null",
      {
        "type": "array",
        "items": "com.danijelsudimac.shipmentservice.model.common.Goods"
      }],
    "default": null
  }, {
    "name" : "orderId",
    "type": [
      "null",
      "string"
    ],
    "default": null
  }, {
    "name" : "originAddress",
    "type" : ["null","com.danijelsudimac.shipmentservice.model.common.Address"],
    "default": null
  }, {
    "name" : "originEmail",
    "type": [
      "null",
      "string"
    ],
    "default": null
  }, {
    "name" : "originName",
    "type": [
      "null",
      "string"
    ],
    "default": null
  }, {
    "name" : "originPhoneNumber",
    "type": [
      "null",
      "string"
    ],
    "default": null
  }, {
    "name" : "recipientAddress",
    "type" : ["null","com.danijelsudimac.shipmentservice.model.common.Address"],
    "default": null
  }, {
    "name" : "recipientEmail",
    "type": [
      "null",
      "string"
    ],
    "default": null
  }, {
    "name" : "recipientName",
    "type": [
      "null",
      "string"
    ],
    "default": null
  }, {
    "name" : "recipientPhoneNumber",
    "type": [
      "null",
      "string"
    ],
    "default": null
  }, {
    "name" : "shippingMethod",
    "type" : ["null","com.danijelsudimac.shipmentservice.model.common.ShippingMethod"],
    "default": null
  }, {
    "name" : "status",
    "type" : ["null","com.danijelsudimac.shipmentservice.model.common.ShipmentStatus"],
    "default": null
  }, {
    "name" : "trackingNumber",
    "type": [
      "null",
      "string"
    ],
    "default": null
  } ]
}