{
  "type" : "record",
  "name" : "Address",
  "namespace" : "com.danijelsudimac.shipmentservice.model.common",
  "fields" : [ {
    "name" : "addressLine",
    "type": [
      "null",
      "string"
    ],
    "default": null
  }, {
    "name" : "city",
    "type": [
      "null",
      "string"
    ],
    "default": null
  }, {
    "name" : "country",
    "type": [
      "null",
      "string"
    ],
    "default": null
  }, {
    "name" : "postalCode",
    "type": [
      "null",
      "string"
    ],
    "default": null
  }, {
    "name" : "state",
    "type": [
      "null",
      "string"
    ],
    "default": null
  } ]
}