{
  "type" : "record",
  "name" : "Item",
  "namespace" : "com.danijelsudimac.shipmentservice.model.common",
  "fields" : [ {
    "name" : "name",
    "type": [
      "null",
      "string"
    ],
    "default": null
  }, {
    "name" : "quantity",
    "type": [
      "null",
      "int"
    ],
    "default": null
  }, {
    "name" : "unit",
    "type": [
      "null",
      "string"
    ],
    "default": null
  }, {
    "name" : "weight",
    "type": [
      "null",
      "double"
    ],
    "default": null
  } ]
}