name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build shipment-service-app
        run: |
          mvn clean package \
            -pl shipment-service-app \
            -am \
            -DskipTests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t shipment-service ./shipment-service-app

      - name: Tag image with SHA
        run: |
          docker tag shipment-service:latest \
          581979856637.dkr.ecr.us-east-2.amazonaws.com/shipment-platform/shipment-service:${{ github.sha }}

      - name: Push SHA image
        run: |
          docker push \
          581979856637.dkr.ecr.us-east-2.amazonaws.com/shipment-platform/shipment-service:${{ github.sha }}

      - name: Tag image with latest
        run: |
          docker tag shipment-service:latest \
          581979856637.dkr.ecr.us-east-2.amazonaws.com/shipment-platform/shipment-service:latest

      - name: Push latest
        run: |
          docker push \
          581979856637.dkr.ecr.us-east-2.amazonaws.com/shipment-platform/shipment-service:latest