name: CD (Deploy to ECS)

on:
  push:
    branches:
      - main
env:
  ECR_REPOSITORY: shipment-platform/shipment-service

jobs:
  docker-image-build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Render ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs/task-definition.json
          container-name: shipment-service
          image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Deploy ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ecs/task-definition.json
          service: shipment-service
          cluster: shipment-cluster
          wait-for-service-stability: true